function [  particle_type, ...
            R, ...
            Lx, ...
            Ly, ...
            Lz, ...
            phi, ...
            phi_target, ...
            position_constraint_axis, ...
            position_constraint_lower, ...
            position_constraint_upper, ...
            orientation_constraint_axis, ...
            orientation_constraint_lower, ...
            orientation_constraint_upper, ...
            sigma_translation_max, ...
            sigma_rotation_max, ...
            sigma_ratio, ...
            number_of_equilibration_sweeps, ...
            delta_phi, ...
            output_file_path] = read_input(file_path)

file_string = fileread(file_path);

particle_type = read_key(file_string, 'particle_type', 'string');

R = read_key(file_string, 'R', 'array');
switch particle_type
    case "sphere"
        number_of_properties = 1;
    case "ellipse"
        number_of_properties = 2;
    case "ellipsoid"
        number_of_properties = 3;
    case "cuboid"
        number_of_properties = 3;
end
number_of_particles = numel(R) / number_of_properties;
R = reshape(R, [number_of_particles, number_of_properties]);

Lx = read_key(file_string, 'domain_size_x', 'scalar');
Ly = read_key(file_string, 'domain_size_y', 'scalar');
Lz = read_key(file_string, 'domain_size_z', 'scalar');
phi = read_key(file_string, 'phi', 'scalar');
phi_target = read_key(file_string, 'phi_target', 'scalar');
position_constraint_axis = read_key(file_string, 'position_constraint_axis', 'string');
position_constraint_lower = read_key(file_string, 'position_constraint_lower', 'scalar');
position_constraint_upper = read_key(file_string, 'position_constraint_upper', 'scalar');
orientation_constraint_axis = read_key(file_string, 'orientation_constraint_axis', 'array');
orientation_constraint_lower = read_key(file_string, 'orientation_constraint_lower', 'scalar');
orientation_constraint_upper = read_key(file_string, 'orientation_constraint_upper', 'scalar');
sigma_translation_max = read_key(file_string, 'sigma_translation_max', 'scalar');
sigma_rotation_max = read_key(file_string, 'sigma_rotation_max', 'scalar');
sigma_ratio = read_key(file_string, 'sigma_ratio', 'scalar');
number_of_equilibration_sweeps = read_key(file_string, 'number_of_equilibration_sweeps', 'scalar');
delta_phi = read_key(file_string, 'delta_phi', 'scalar');
output_file_path = read_key(file_string, 'output_file_path', 'string');

end

